all:
  children:
    rosa:
      hosts:
        # === ROSA Cluster (프로덕션) ===
        dr-rosa-cluster:
          ansible_connection: local
          kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/rosa-config"

        # === Local Tekton (테스트용) ===
        # local-tekton-cluster:  # dr-rosa-cluster 대신 로컬 사용
        #   ansible_connection: local
        #   ansible_host: 10.2.2.40
        #   kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config-tekton"  # K3s config
      vars:
        rosa_cluster_name: dr-rosa-cluster
        aws_region: ap-northeast-2

# ROSA 클러스터 Kubeconfig 생성 절차
# 현재 Terraform 코드(modules/rosa/main.tf)는 실제 ROSA 클러스터를 생성 X
# 따라서 실제 ROSA 클러스터를 구축(rosa create cluster ...) 하신 후에, 아래 명령어를 순서대로 실행하여 kubeconfig를 생성.
# 관리자 계정 생성 클러스터 이름은 environments/dr/main.tf에서 정의된 대로 dr-rosa-cluster라고 가정.


# ⚠️ 사용자 조치 필요: inventory/hosts.yml 파일 내용을 확인하시고, 
# 실제 ROSA 클러스터의 API URL과 접속 정보를 채워 넣어주세요. (주석 가이드 참고)

# 이제 ansible-playbook -i inventory/hosts.yml playbooks/deploy_all.yml 명령으로 
# ROSA 배포를 시도하실 수 있습니다. (단, dr-worker 이미지 빌드 선행 필요)

# rosa create admin --cluster=dr-rosa-cluster
# 출력 예시:
# Admin account has been created for cluster 'dr-rosa-cluster'
# Username: cluster-admin
# Password: <임의의_비밀번호>
# API URL: https://api.dr-rosa-cluster.abcd.p1.openshiftapps.com:6443

# oc login https://api.dr-rosa-cluster.abcd.p1.openshiftapps.com:6443 --username cluster-admin --password <임의의_비밀번호>
# 로그인 및 파일 저장 (가장 중요한 단계) 위에서 출력된 oc login 명령어 뒤에 --kubeconfig 옵션을 붙여서 실행.


# # 예시 (위에서 나온 API URL과 Password를 넣어주세요)
# oc login <API_URL> --username cluster-admin --password <PASSWORD> --kubeconfig=~/.kube/rosa-config

# 검증
# kubectl get nodes --kubeconfig=~/.kube/rosa-config